const _ = require('lodash')
const rs = require('randomstring')

console.log('30 998244353')
console.log('26')

console.log('A->' + rs.generate({ length: 100, charset: 'B' }))
console.log('B->' + rs.generate({ length: 100, charset: 'C' }))
console.log('C->' + rs.generate({ length: 100, charset: 'D' }))
console.log('D->' + rs.generate({ length: 100, charset: 'E' }))
console.log('E->' + rs.generate({ length: 100, charset: 'F' }))
console.log('F->' + rs.generate({ length: 100, charset: 'G' }))
console.log('G->' + rs.generate({ length: 100, charset: 'H' }))
console.log('H->' + rs.generate({ length: 100, charset: 'I' }))
console.log('I->' + rs.generate({ length: 100, charset: 'J' }))
console.log('J->' + rs.generate({ length: 100, charset: 'K' }))
console.log('K->' + rs.generate({ length: 100, charset: 'L' }))
console.log('L->' + rs.generate({ length: 100, charset: 'M' }))
console.log('M->' + rs.generate({ length: 100, charset: 'N' }))
console.log('N->' + rs.generate({ length: 100, charset: 'O' }))
console.log('O->' + rs.generate({ length: 100, charset: 'P' }))
console.log('P->' + rs.generate({ length: 100, charset: 'Q' }))
console.log('Q->' + rs.generate({ length: 100, charset: 'R' }))
console.log('R->' + rs.generate({ length: 100, charset: 'S' }))
console.log('S->' + rs.generate({ length: 100, charset: 'T' }))
console.log('T->' + rs.generate({ length: 100, charset: 'U' }))
console.log('U->' + rs.generate({ length: 100, charset: 'V' }))
console.log('V->' + rs.generate({ length: 100, charset: 'W' }))
console.log('W->' + rs.generate({ length: 100, charset: 'X' }))
console.log('X->' + rs.generate({ length: 100, charset: 'Y' }))
console.log('Y->' + rs.generate({ length: 100, charset: 'Z' }))
console.log('Z->' + rs.generate({ length: 100, charset: '1234567890' }))